services:
  discord-bot:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.50"
    #       memory: 2048M
    #     reservations:
    #       cpus: "0.25"
    #       memory: 512M